# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\tetsuya\Documents\motor_yao\Design01.cydsn\Design01.cyprj
# Date: Sun, 11 Feb 2018 09:20:45 GMT
#set_units -time ns
create_clock -name {Clock_4(routed)} -period 10000000 -waveform {0 5000000} [list [get_pins {ClockBlock/dclk_5}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {UART_1_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 313 627} [list [get_pins {ClockBlock/dclk_glb_3}]]
create_generated_clock -name {UART_PS3_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 1251 2501} -nominal_period 52083.333333333328 [list [get_pins {ClockBlock/dclk_glb_4}]]
create_generated_clock -name {Clock_3} -source [get_pins {ClockBlock/clk_sync}] -edges {1 9 19} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/clk_sync}] -edges {1 9 19} [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {Clock_2} -source [get_pins {ClockBlock/clk_sync}] -edges {1 9 19} [list [get_pins {ClockBlock/dclk_glb_2}]]
create_generated_clock -name {Clock_4} -source [get_pins {ClockBlock/clk_sync}] -edges {1 240001 480001} [list [get_pins {ClockBlock/dclk_glb_5}]]


# Component constraints for C:\Users\tetsuya\Documents\motor_yao\Design01.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\tetsuya\Documents\motor_yao\Design01.cydsn\Design01.cyprj
# Date: Sun, 11 Feb 2018 09:20:38 GMT
