/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "motorD.h"
#include "high1_1_aliases.h"
#include "high1_1.h"
#include "low1_1_aliases.h"
#include "low1_1.h"
#include "high1_2_aliases.h"
#include "high1_2.h"
#include "low1_2_aliases.h"
#include "low1_2.h"
#include "reverse_D.h"
#include "Clock_1.h"
#include "led_aliases.h"
#include "led.h"
#include "motorB.h"
#include "high2_1_aliases.h"
#include "high2_1.h"
#include "low2_1_aliases.h"
#include "low2_1.h"
#include "high2_2_aliases.h"
#include "high2_2.h"
#include "low2_2_aliases.h"
#include "low2_2.h"
#include "reverse_B.h"
#include "Clock_2.h"
#include "motorC.h"
#include "high3_1_aliases.h"
#include "high3_1.h"
#include "low3_1_aliases.h"
#include "low3_1.h"
#include "high3_2_aliases.h"
#include "high3_2.h"
#include "low3_2_aliases.h"
#include "low3_2.h"
#include "reverse_C.h"
#include "Clock_3.h"
#include "UART_PS3.h"
#include "ISR_PS3.h"
#include "UART_1.h"
#include "isr1.h"
#include "Clock_4.h"
#include "UART_PS3_IntClock.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

